name: Deploy Cloudflare Workers

on:
  push:
    branches:
      - main
    paths:
      - "workers/**"
      - "Cargo.toml"
      - "Cargo.lock"

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      sample-worker: ${{ steps.changes.outputs.sample-worker }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            sample-worker:
              - "workers/sample-worker/**"
              - "Cargo.toml"
              - "Cargo.lock"

  deploy:
    needs: detect-changes
    strategy:
      matrix:
        worker: [sample-worker]
    runs-on: ubuntu-latest
    if: ${{ needs.detect-changes.outputs[matrix.worker] == 'true' }}
    steps:
      - uses: actions/checkout@v4
      - name: Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: workers/${{ matrix.worker }}
